name = "gameoflife"
description = "Game of Life implementation in Ada using OpenGL and GLFW for redering"
version = "0.1.0-dev"

authors = ["José Antonio Verde Jiménez"]
maintainers = ["José Antonio Verde Jiménez <joseaverde@protonmail.com>"]
maintainers-logins = ["joseaverde"]
licenses = "GPL-3.0-or-later"
website = "https://github.com/joseaverde/gameoflife"
tags = ["game", "conway"]

[[depends-on]]
openglada_glfw = "~0.9.0"

[build-switches]

"*".ada_version    = "Ada2022"
"*".style_checks = [ "-gnaty3"          # Indentation to 3
                   , "-gnatya"          # Check attribute casing
                   , "-gnatyA"          # Check array attribute indexes
                   , "-gnatyb"          # No blanks at end of lines
                   , "-gnatyC"          # Comment format: 1 space (-- comment)
                   , "-gnatyd"          # No DOS line terminators
                   , "-gnatye"          # end/exit labels present
                   , "-gnatyf"          # No form feeds or vertical tabs
                   , "-gnatyh"          # No horizontal tabs
                   , "-gnaty-I"         # `in' is required in parameters
                   , "-gnatyk"          # Check casing rules for keywords
                   # , "-gnatyL6"         # Maximum nesting level
                   , "-gnatyM79"        # Maximum 79 characters.
                   , "-gnatyn"          # Check casing of package Standard identifiers
                   , "-gnatyO"          # Check overriding indicators
                   , "-gnatyp"          # Check pragma casing
                   , "-gnatyr"          # Check casing for identifier references
                   # , "-gnatyt"          # Check token separation rules
                   , "-gnatyu"          # Check no unnecessary blank lines
                   , "-gnatyx"          # Check extra parenthesis around conditionals
                   ]
